# Generated by Django 6.0.3 on 2026-04-03 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dadjokes", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="joke",
            name="jokester",
            field=models.CharField(),
        ),
        migrations.AlterField(
            model_name="picture",
            name="image_url",
            field=models.URLField(),
        ),
        migrations.AlterField(
            model_name="picture",
            name="jokester",
            field=models.CharField(),
        ),
    ]
