# Generated by Django 6.0.1 on 2026-02-12 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Profile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("username", models.TextField()),
                ("display_name", models.TextField()),
                ("profile_image_url", models.URLField(blank=True)),
                ("text", models.TextField()),
                ("join_date", models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
