# Generated by Django 6.0.3 on 2026-04-20 01:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Trail",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("region", models.CharField(max_length=100)),
                ("latitude", models.FloatField()),
                ("longitude", models.FloatField()),
                ("distance_miles", models.FloatField()),
                ("elevation_gain_ft", models.IntegerField()),
                (
                    "difficulty",
                    models.CharField(
                        choices=[
                            ("easy", "Easy"),
                            ("moderate", "Moderate"),
                            ("hard", "Hard"),
                            ("expert", "Expert"),
                        ],
                        max_length=20,
                    ),
                ),
                ("is_loop", models.BooleanField(default=True)),
                ("description", models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name="Profile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("home_latitude", models.FloatField()),
                ("home_longitude", models.FloatField()),
                ("home_location", models.CharField(max_length=200)),
                (
                    "experience_level",
                    models.CharField(
                        choices=[
                            ("beginner", "Beginner"),
                            ("intermediate", "Intermediate"),
                            ("advanced", "Advanced"),
                        ],
                        default="beginner",
                        max_length=20,
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="project_profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="GearItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("shelter", "Shelter"),
                            ("sleep", "Sleep System"),
                            ("cook", "Cook Kit"),
                            ("clothing", "Clothing"),
                            ("pack", "Pack/Bag"),
                            ("electronics", "Electronics"),
                            ("safety", "Safety/First Aid"),
                            ("other", "Other"),
                        ],
                        max_length=50,
                    ),
                ),
                ("weight_oz", models.FloatField()),
                ("temp_rating_f", models.IntegerField(blank=True, null=True)),
                ("is_rain_gear", models.BooleanField(default=False)),
                ("is_snow_gear", models.BooleanField(default=False)),
                ("brand", models.CharField(blank=True, max_length=100)),
                (
                    "profile",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="project.profile",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Trip",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("start_date", models.DateField()),
                ("end_date", models.DateField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("planning", "Planning"),
                            ("ready", "Ready"),
                            ("completed", "Completed"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="planning",
                        max_length=20,
                    ),
                ),
                ("notes", models.TextField(blank=True)),
                (
                    "profile",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="project.profile",
                    ),
                ),
                (
                    "trail",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="project.trail"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="PackListItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("quantity", models.PositiveIntegerField(default=1)),
                ("is_packed", models.BooleanField(default=False)),
                (
                    "gear_item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="project.gearitem",
                    ),
                ),
                (
                    "trip",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="project.trip"
                    ),
                ),
            ],
        ),
    ]
