# Generated by Django 6.0.3 on 2026-04-29 01:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("project", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="trail",
            name="max_nights",
            field=models.IntegerField(default=3),
        ),
        migrations.AddField(
            model_name="trail",
            name="min_nights",
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name="gearitem",
            name="category",
            field=models.CharField(
                choices=[
                    ("Shelter", "Shelter"),
                    ("Sleep System", "Sleep System"),
                    ("Cook Kit", "Cook Kit"),
                    ("Clothing", "Clothing"),
                    ("Pack/Bag", "Pack/Bag"),
                    ("Electronics", "Electronics"),
                    ("Safety/First Aid", "Safety/First Aid"),
                    ("Other", "Other"),
                ],
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="profile",
            name="experience_level",
            field=models.CharField(
                choices=[
                    ("Beginner", "Beginner"),
                    ("Intermediate", "Intermediate"),
                    ("Advanced", "Advanced"),
                ],
                default="Beginner",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="trail",
            name="difficulty",
            field=models.CharField(
                choices=[
                    ("Easy", "Easy"),
                    ("Moderate", "Moderate"),
                    ("Hard", "Hard"),
                    ("Expert", "Expert"),
                ],
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="trip",
            name="status",
            field=models.CharField(
                choices=[
                    ("Planning", "Planning"),
                    ("Ready", "Ready"),
                    ("Completed", "Completed"),
                    ("Cancelled", "Cancelled"),
                ],
                default="Planning",
                max_length=20,
            ),
        ),
    ]
